name: ci  # Name of the GitHub Actions workflow file, short for "Continuous Integration"

on:
  push:  # Specifies that this workflow will run whenever there is a push to the repository

jobs:  # Defines the jobs that will run as part of this workflow
  docker:  # Name of the job
    runs-on: ubuntu-latest  # Specifies that the job should run on the latest Ubuntu runner provided by GitHub Actions
    steps:  # Defines the sequence of steps to execute in the job

      - name: Login to Docker Hub  # Step 1: Login to Docker Hub
        uses: docker/login-action@v3  # Uses a pre-built GitHub Action to log in to Docker Hub
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}  # Uses the username stored in GitHub repository variables
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Uses the Docker Hub token stored securely in GitHub secrets

      - name: Set up QEMU  # Step 2: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3  # Uses a GitHub Action to configure QEMU, enabling cross-platform builds with Docker

      - name: Set up Docker Buildx  # Step 3: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Uses a GitHub Action to configure Docker Buildx, a utility for advanced Docker builds

      - name: Build and push  # Step 4: Build and push the Docker image
        uses: docker/build-push-action@v6  # Uses a GitHub Action to build and push Docker images
        with:
          push: true  # Ensures the Docker image is pushed to Docker Hub after building
          tags: user/app:latest  # Tags the Docker image with "user/app:latest"; replace "user" with your Docker Hub username
